---
language: python
services:
  - docker

# Build matrix
env:
  global:
    - ROLENAME=chrony
  matrix:
    - DISTRIBUTION=centos7
    - DISTRIBUTION=debian9
    - DISTRIBUTION=ubuntu16.04
    - DISTRIBUTION=ubuntu18.04

install:
  - pip install molecule docker

before_script:
  - cd ..
  - mv ansible-role-$ROLENAME frzk.$ROLENAME
  - cd frzk.$ROLENAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
...
