---
- name: Update pacman cache
  community.general.pacman:
    update_cache: yes

- name: Install dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - build-essential
    - systemd
    - libssl-dev
    - python3
    - python3-pip

- name: Update some pip modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: latest
  loop:
    - pip
    - setuptools
    - wheel

- name: Install pip modules
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - ansible
    - molecule[docker]
    - docker
...
