# Dockerfiles are maintained in a central repo available at https://github.com/Frzk/docker-ansible-images
#
{{ lookup('url', 'https://raw.githubusercontent.com/Frzk/docker-ansible-images/main/' ~ item.image ~ '/Dockerfile', split_lines=False) }}
