---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "${WRKFLW_DISTRIB:-centos7}:latest"
    command: ${WRKFLW_DOCKER_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: false
scenario:
  name: default
  test_sequence:
    # - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - destroy
provisioner:
  name: ansible
  host_vars:
    # setting for the platform instance named 'instance'
    instance:
      ansible_user: ansible
  # Ansible options:
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
...
