---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint -c molecule/default/yamllint.yml .
  ansible-lint
  flake8
lint:
  name: yamllint
  options:
    config-file: molecule/default/yamllint.yml
platforms:
  - name: instance
    image: "kblr/${MOLECULE_DISTRIB:-centos7}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
...
