---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: "${WRKFLW_DISTRIB}"
    command: "${WRKFLW_DOCKER_COMMAND:-/sbin/init}"
    systemd: always
    privileged: true
    pre_build_image: false
scenario:
  name: default
  test_sequence:
    # - lint: linting is done in GitHub Workflow.
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      # setting for the platform instance named 'instance'
      # described on line 7 of this file:
      instance:
        ansible_connection: podman
        ansible_user: ansible
        ansible_python_interpreter: auto_silent
  # Ansible options:
  env:
    ANSIBLE_VERBOSITY: 3
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
...
