---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ${WRKFLW_DISTRIB}
    command: ${WRKFLW_DOCKER_COMMAND:-"/sbin/init"}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - NET_BIND_SERVICE
      - NET_RAW
    privileged: false
    pre_build_image: false
scenario:
  name: default
  test_sequence:
    # - lint: linting is done in GitHub Workflow.
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    # - side_effect
    - verify
    - cleanup
    - destroy
provisioner:
  name: ansible
  log: true
  inventory:
    host_vars:
      # setting for the platform instance named 'instance'
      instance:
        ansible_user: ansible
  # Ansible options:
  config_options:
    defaults:
      stdout_callback: yaml
verifier:
  name: ansible
...
