---
- name: Prepare
  hosts: all
  tasks:
    - name: Packages
      block:
        - name: Install packages
          ansible.builtin.package:
            name: "{{ item }}"
            state: present
          loop:
            - "sudo"

    - name: wheel Group
      block:
        - name: Create `wheel` group
          ansible.builtin.group:
            name: "wheel"
            system: yes
            state: present

    - name: Ansible User
      block:
        - name: Create ansible user
          ansible.builtin.user:
            name: ansible
            comment: Ansible User
            groups:
              - wheel
            state: present

        - name: Create sudoers.d dropin
          ansible.builtin.file:
            path: "/etc/sudoers.d/"
            owner: root
            group: root
            mode: 0750
            state: directory

        - name: Allow user ansible to sudo (1)
          ansible.builtin.lineinfile:
            path: "/etc/sudoers.d/wheel"
            line: "%wheel ALL=(ALL) NOPASSWD:ALL"
            insertbefore: BOF
            create: yes
            owner: root
            group: root
            mode: 0440
            state: present

        - name: Allow user ansible to sudo (2)
          ansible.builtin.lineinfile:
            path: "/etc/sudoers"
            line: "@includedir /etc/sudoers.d"
            insertafter: EOF
            create: yes
            owner: root
            group: root
            mode: 0640
            state: present
...
